language: node_js
node_js:
- 6.0.0
branches:
  only:
  - master

install: npm install

before_script:
- git config --global user.name "Sergio Carracedo"
- git config --global user.email "info@sergiocarracedo.es"

script: npm run build