language: node_js
node_js:
- 10.13.0
branches:
  only:
  - master

install: yarn && cd themes/sergiocarracedo && yarn && cd ../..

before_script:
- git config --global user.name "Sergio Carracedo"
- git config --global user.email "info@sergiocarracedo.es"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: yarn build