baseURL: 'https://sergiocarracedo.es/'
languageCode: 'en-us'
defaultContentLanguage: 'en'
title: 'Sergio Carracedo'

theme: 'sergiocarracedo'

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 1

# Enable global emoji support
enableEmoji: true

params:
  keywords:
  description: Sergio Carracedo's personal page and blog
  author: Sergio Carracedo
  GA: 'G-87X78TXEGE'
  disqus: sergiocarracedo.disqus.com
  favicon: 'favicon.png'
  mainSections: ["posts"]
  images:
    - '/i/cover.jpg'

permalinks:
  '/2021': '/:slug'
  '/2022': '/:slug'
  '/2023': '/:slug'
  '/2024': '/:slug'
