name = "sergiocarracedo"
license = "MIT"
licenselink = ""
description = ""
homepage = "https://sergiocarracedo.es/"
tags:
features = []

min_version = "0.83.0"

author:
  name = "Sergio Carracedo"
  homepage = "https://sergiocarracedo.es"
